### ISSUE TITLE
setuptools

### ISSUE THREAD

**Issue by thejerwang** [bakera1/CreditDefaultSwapPricer#1]
Hi Alexander, 

Thank you for this. I just wondered if it's easy enough to use setuptools so this can be published to pypi and allow peopel to use pip install? 

Thank you.

**Comment by bakera1** [comment]
Hi quantransform,

Thank you for the feedback; adding a setup.py and publishing to pypi, I agree would be pretty useful steps.  

This would involve translating the build scripts steps into the equivalent setup.py representation. This mapping exercise should in theory be pretty straight forward, as plenty of tutorials on the web which explain how to achieve this.

Alexander

**Comment by quantransform** [comment]
Hi Alexander,

Thank you for the quick reply. I am familiar with setup.py to build up packages with .py files or cythpn but not 100% sure how to do swig. If you can give me some guidence, I am happy to give a go to see if I can make it work. 

Thanks.

**Comment by bakera1** [comment]
I have now added a setup.py with two batch files, windows & linux, perhaps you can try these out to see if these build successfully. On windows I have only tested the gcc compiler in README not cl.exe which I think will have issues. The swig build step does not build via the setup.py, I did write a version that included both modules, but experienced some issues related to the .cpp generated which I need to go back and resolve. It should be possible to build the isda_wrap.cxx as isda_wrap.cpp in a setup step; for now this is a one off step since this doesn't change that often only when you add a new function to the isda.h file. 

Regards

Alex

**Comment by bakera1** [comment]
Hi, 

This project has now been upgraded to python3 and the Microsoft compiler and a windows wheel published to pypi. This will avoid any compilation steps on windows; I have additionally tested on Ubuntu 16.04 and a similar wheel can be built but sadly not published to pypi (yet).

$python -m venv test1
$cd test1
$Scripts\activate.bat
$cd test1
$ pip install isda
$ copy Lib\site-packages\isda\tests\TestCdsPricerIndex.py 
$python TestCdsPricerIndex.py

You should output to the screen that looks like below.

(test1) C:\sandbox\test5>python TestCdsPricerIndex.py
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 422.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 422.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 423.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 420.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 415.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 414.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 429.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 409.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 400.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 405.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 419.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 400.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 406.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 413.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 422.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 422.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 409.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 428.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 414.0 (ms)
cob_date: 08/01/2018 pv_dirty: -2792.666875 pv_clean: -2797.527986 ai: 4.861111 wall_time: 416.0 (ms)
factoral 120
average execution (415.4,)
.
----------------------------------------------------------------------
Ran 1 test in 8.319s

OK

(test1) C:\sandbox\test1>

**Comment by bakera1** [comment]
1.0.3 also now includes a new call to cds_index_all_in_one which supports a more efficient CDS index pricing.

**Comment by bakera1** [comment]
1.0.3 also now includes a new call to cds_index_all_in_one which supports a more efficient CDS index pricing.
