### ISSUE TITLE
infinite loop in bootstrap

### ISSUE THREAD

**Issue by derekholmes** [bakera1/CreditDefaultSwapPricer#10]
I am experiencing an infinite loop in main.c  with an unbounded attempt at bootstrapping a curve.
not sure why you are changing the recovery rate at recoveryRate -= 0.01.
Any ideas while I try to come up with  reproduceable example?

**Comment by bakera1** [comment]
Derek, names that are close to default can often have recovery rates that are inconsistent with the upfront or par spread assumptions; to this end making a very small change to the recovery rate can coax names close to default to bootstrap and price. If you are invoking this logic; it is probably related to the underlying spreads resulting in negative hazard rates. If you can clone the test and include your spreads I can take a closer look. Alex

**Comment by derekholmes** [comment]
Alex, I found the issue.  I am calling CreditDefaultPricer via R and reticulate.
The issue is that the swap par rates were sent to the package in alphabetical order instead of maturity order, which I assume created negative RF forward rates.  (I was using spreads near par, so I knew there were no negative hazard rates)This did create an infinite loop as JpmcdsCleanSpreadCurve (Main.c :134) could not bootstrap a curve, and the iteration does not depend on rf curves.
Thanks for the response, I would kindly suggest an iteration counter or other flag in that loop to avoid others making the same mistake.
Rgds- Derek Holmes, old credit trader.
    On Tuesday, December 22, 2020, 05:37:11 AM CST, Alexander Baker <notifications@github.com> wrote:  
 
 


Closed #10.

**Comment by bakera1** [comment]
Derek,

Yes the bootstrapping will assume relatively monotonically changing par spreads; agree would be useful to refine with a max_counter and a default to prevent going forward. Have number of changes backed up on this library; will add to the next merge request.

Thanks Alex.
