### ISSUE TITLE
Documentation regarding using the library

### ISSUE THREAD

**Issue by ghost** [bakera1/CreditDefaultSwapPricer#7]
We need documentation regarding how to use this library. 

Seems you expect users to look at test cases py files to figure out how to use the module?

On Ubuntu it is located in folder isda/tests and following files need to be reviewed regarding how to use the module.

**Comment by bakera1** [comment]
Hi, agree this would be a sensible enhancement; need to find some time to document the test cases properly to help figure out the different features. Noted!

**Comment by ghost** [comment]
Can you explain how to use your code to get the upfront payment amount
